name: Deploy Game

on:
  push:
    branches: [ main, development ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Game
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        destination_dir: .
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy game version from ${{ github.ref_name }}'
        tag_name: '${{ github.ref_name }}-v${{ github.run_number }}'
        tag_message: 'Deployment from ${{ github.ref_name }} branch' 